Modernize

diff --git a/fs/functions/_map b/fs/functions/_map
--- a/fs/functions/_map
+++ b/fs/functions/_map
@@ -7,6 +7,12 @@ function _map {
   shift
   local args="$*"
 
+  # Validate function name contains only safe characters
+  if [[ ! "$fn_arg" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
+    printf "Error: Invalid function name '%s' for map\n" "$fn_arg" >&2
+    exit 1
+  fi
+
   if [ "$(declare -f "$fn_arg" > /dev/null; echo $?)" -gt 0 ]; then
     printf "%s %s\n" "$fn_arg" "is not a valid function for map" >&2
     exit 1
@@ -22,7 +28,8 @@ function _map {
   IFS=''
 
   while read -r line; do
-    eval "$fn_arg" "'$line'" "'$args'"
+    # Use safer function call instead of eval
+    "$fn_arg" "$line" "$args"
   done < /dev/stdin
 
   IFS=$old_ifs
